"""empty message

Revision ID: 09da2a34e18f
Revises: 531457e36068
Create Date: 2024-12-09 00:15:50.625720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09da2a34e18f'
down_revision = '531457e36068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorites_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###
