"""empty message

Revision ID: 531457e36068
Revises: 0e5c2bdfbe89
Create Date: 2024-12-08 15:01:00.698436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531457e36068'
down_revision = '0e5c2bdfbe89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_user.id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_character.id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planet.id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])
        batch_op.drop_column('character.id')
        batch_op.drop_column('user.id')
        batch_op.drop_column('planet.id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet.id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user.id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character.id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_planet.id_fkey', 'planet', ['planet.id'], ['id'])
        batch_op.create_foreign_key('favorites_character.id_fkey', 'character', ['character.id'], ['id'])
        batch_op.create_foreign_key('favorites_user.id_fkey', 'user', ['user.id'], ['id'])
        batch_op.drop_column('character_id')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
